In [6]:
import torch 

a = torch.tensor([[1., 2, 3], [4, 5, 6], [7, 8, 9]])
torch.einsum("ii->", a)

tensor(15.)

In [7]:
torch.einsum("ij, jk->ik", a, a)

tensor([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [8]:
b = torch.tensor([1, 2, 3])
b = b.unsqueeze(1)
b.expand_as(a)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [10]:
a.unsqueeze(-1).repeat_interleave(5, dim=-1)

tensor([[[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.]],

        [[4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6.]],

        [[7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8.],
         [9., 9., 9., 9., 9.]]])

In [11]:
a = torch.zeros((4, 3, 2))
b = torch.zeros((4, 3, 3))
c = torch.concat((a, b), dim=-1)
c.shape

torch.Size([4, 3, 5])

In [ ]:
def get_stats(ids, counts=None):
    """
    Given a list of integers, return a dictionary of counts of consecutive pairs
    Example: [1, 2, 3, 1, 2] -> {(1, 2): 2, (2, 3): 1, (3, 1): 1}
    Optionally allows to update an existing dictionary of counts
    """
    counts = {} if counts is None else counts
    for pair in zip(ids, ids[1:]): # iterate consecutive elements
        counts[pair] = counts.get(pair, 0) + 1
    return counts


def merge(ids, pair, idx):
    """
    In the list of integers (ids), replace all consecutive occurrences
    of pair with the new integer token idx
    Example: ids=[1, 2, 3, 1, 2], pair=(1, 2), idx=4 -> [4, 3, 4]
    """
    newids = []
    i = 0
    while i < len(ids):
        # if not at the very last position AND the pair matches, replace it
        if ids[i] == pair[0] and i < len(ids) - 1 and ids[i+1] == pair[1]:
            newids.append(idx)
            i += 2
        else:
            newids.append(ids[i])
            i += 1
    return newids

In [35]:
import numpy as np 
a = np.array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0]).astype("bool")

n = len(a)
ans = np.full(n, -1, dtype=int)
indices = np.arange(n)
true_pos = np.where(a)[0]
insert_pos = np.searchsorted(true_pos, indices, side="right") - 1
insert_pos

array([-1, -1, -1,  0,  0,  1,  2,  2,  3,  4,  4,  4,  4,  5,  5])

In [33]:
true_pos

array([ 3,  5,  6,  8,  9, 13])

In [36]:
valid_mask = insert_pos >= 0
ans[valid_mask] = indices[valid_mask] - true_pos[insert_pos[valid_mask]]
ans

array([-1, -1, -1,  0,  1,  0,  0,  1,  0,  0,  1,  2,  3,  0,  1])

In [2]:
import heapq 

a = [(4,"A"), (5,"B"), (1,"C"), (2,"D"), (6, "E"), (3,"F")]
heapq.heapify(a)
b = heapq.heappop(a)
b

(1, 'C')

In [3]:
b = heapq.heappop(a)
b

(2, 'D')

In [5]:
a = [(4,"A"), (5,"B"), (1,"C"), (2,"D"), (6, "E"), (3,"F")]
heapq.nsmallest(3, a)

[(1, 'C'), (2, 'D'), (3, 'F')]

In [7]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
np.cumsum(a, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [10]:
b = np.cumsum(a, axis=0)
b

array([[1, 2, 3],
       [5, 7, 9]])

In [11]:
np.cumsum(b, axis=1)

array([[ 1,  3,  6],
       [ 5, 12, 21]])

In [1]:
from sortedcontainers import SortedList
a = SortedList([4,1,2,5])
a.bisect_left(3)

2

In [2]:
a[2]

4

In [3]:
a[1]

2

In [4]:
a.bisect_right(3)

2

In [5]:
len(a)

4