In [2]:
from sortedcontainers import SortedList
pq = SortedList([4, 3, 3, 2, 1])
pq

SortedList([1, 2, 3, 3, 4])

In [3]:
pq.remove(3)
pq

SortedList([1, 2, 3, 4])

In [4]:
import torch 
a = torch.zeros((5, 10))
a.T

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [10]:
import torch
a = torch.zeros((2, 2, 2))
b = torch.tensor([0, 1])
a.masked_fill(b == 0, -1)

tensor([[[-1.,  0.],
         [-1.,  0.]],

        [[-1.,  0.],
         [-1.,  0.]]])

In [13]:
seq_len = 4
torch.tril(torch.ones((seq_len, seq_len)))

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])

In [1]:
a = "abc"
b = "def"
a + b * 3

'abcdefdefdef'

In [1]:
a = [[1,2], [3,4]]
x, y = a[0]
x

1

In [ ]:
[["0","0","0","1","0","1","1","1"],
 ["0","1","1","0","0","1","0","1"],
 ["1","0","1","1","1","1","0","1"],
 ["0","0","0","1","0","0","0","0"],
 ["0","0","1","0","0","0","1","0"],
 ["1","1","1","0","0","1","1","1"],
 ["1","0","0","1","1","0","0","1"],
 ["0","1","0","0","1","1","0","0"],
 ["1","0","0","1","0","0","0","0"]]

In [1]:
import numpy as np 
import torch
import polars as pl 


class MLP(torch.nn.Module):
    def __init__(self, input_size: int, output_size: int, hidden_dims: str, activation: str = "relu"):
        super().__init__()
        if hidden_dims:
            hidden_sizes = hidden_dims.split(",")
            self.net = torch.nn.Sequential()
            in_size = input_size
            for i, h in enumerate(hidden_sizes):
                h_size = int(h)
                self.net.add_module(f"linear_{i}", torch.nn.Linear(in_size, h_size))
                if activation == "relu":
                    self.net.add_module(f"relu_{i}", torch.nn.ReLU())
                elif activation == "tanh":
                    self.net.add_module(f"tanh_{i}", torch.nn.Tanh())
                else:
                    raise ValueError(f"Unsupported activation: {activation}")
                in_size = h_size
            self.net.add_module("output", torch.nn.Linear(in_size, output_size))
        else:
            # linear model
            self.net = torch.nn.Linear(input_size, output_size)

    def forward(self, x):
        out = self.net(x)
        return out

In [2]:
model = MLP(input_size=10, output_size=1, hidden_dims="20,10", activation="relu")
x = torch.randn(5, 10)
output = model(x)
print(output)

tensor([[ 0.0593],
        [-0.0667],
        [-0.0618],
        [-0.0437],
        [-0.0840]], grad_fn=<AddmmBackward0>)


In [14]:
a = [x for x in range(1000)]
import numpy as np 
a = np.array(a)
a.var()

np.float64(83333.25)

In [20]:
a = [1, 2, 3, 4, 5]
a[2::-1] + a[3:]

[3, 2, 1, 4, 5]

In [23]:
import math

def get_rows(col, width):
    ans = 0
    col = col.split(" ")
    w = 0
    lines = []

    for word in col:
        l = len(word)

        if l > width:
            ans += math.ceil(l / width)
            w = 0

        if w < l:
            ans += 1
            w = width
            lines.append([])
        w = w - l - 1
        lines[-1].append(word)
    print(lines)
    return ans

def work(col1, col2, width):
    left = 1
    right = width - 1
    while left < right:
        mid = (left + right) // 2
        r_left = get_rows(col1, mid)
        r_right = get_rows(col2, width - mid)
        if r_left > r_right:
            left = mid + 1
        else:
            right = mid
    if left == 1:
        return left
    r1_left = get_rows(col1, left - 1)
    r1_right = get_rows(col2, width - (left - 1))
    r1 = max(r1_left, r1_right)
    r2_left = get_rows(col1, left)
    r2_right = get_rows(col2, width - left)
    r2 = max(r2_left, r2_right)
    if r1 < r2:
        return left - 1
    else:
        return left


In [24]:
get_rows("This is a sample", 10)

[['This', 'is', 'a'], ['sample']]


2

In [ ]:
class Solution:
    def maxPoints(self, points: List[List[int]]) -> int:
        import math
        
        n = len(points)
        cnt = {}
        for i in range(n - 1):
            for j in range(i + 1, n):
                xi, yi = points[i]
                xj, yj = points[j]
                if xi == xj:
                    slope = (None, None)
                elif yi == yj:
                    slope = (0, 0)
                else:
                    sign = ((xj - xi) * (yj - yi)) > 0
                    xd = abs(xj - xi)
                    yd = abs(yj - yi)
                    g = math.gcd(xd, yd)
                    if sign:
                        slope = (xd // g, yd // g)
                    else:
                        slope = (xd // g, -yd // g)

                if xi == xj:
                    intercept = (None, xi)
                elif yi == yj:
                    intercept = (1, yi)
                else:
                    numerator = xj * yi - xi * yj
                    denominator = xj - xi
                    sign = (numerator * denominator) > 0
                    xd = abs(numerator)
                    yd = abs(denominator)
                    g = math.gcd(xd, yd)
                    if sign:
                        intercept = (xd // g, yd // g)
                    else:
                        intercept = (xd // g, -yd // g)
                
                cnt[(slope, intercept)] = cnt.get((slope, intercept), 0) + 1
        
        max_v = 0
        for k, v in cnt.items():
            if v > max_v:
                max_v = v
        k = int((1.0 + math.sqrt(1 + 8 * max_v)) / 2)
        return k
        

In [ ]:
import numpy as np

class Node:
    def __init__(self, point, left=None, right=None, axis=None):
        self.point = point
        self.left = left
        self.right = right
        self.axis = axis

class KDTree:
    def __init__(self, points, k=None):
        """
        Build a K-d tree from a list of points.
        
        Args:
            points: List of points (each point is a list/array of coordinates)
            k: Number of dimensions (inferred from points if not provided)
        """
        self.points = np.array(points)
        self.k = k if k is not None else self.points.shape[1]
        self.root = self._build(self.points, depth=0)
    
    def _build(self, points, depth):
        """Recursively build the K-d tree."""
        if len(points) == 0:
            return None
        
        # Select axis based on depth (cycle through dimensions)
        axis = depth % self.k
        
        # Sort points by the current axis and choose median
        sorted_points = points[points[:, axis].argsort()]
        median_idx = len(sorted_points) // 2
        
        # Create node and recursively build subtrees
        return Node(
            point=sorted_points[median_idx],
            left=self._build(sorted_points[:median_idx], depth + 1),
            right=self._build(sorted_points[median_idx + 1:], depth + 1),
            axis=axis
        )
    
    def nearest_neighbor(self, query_point):
        """Find the nearest neighbor to the query point."""
        query_point = np.array(query_point)
        best = [None, float('inf')]  # [best_point, best_distance]
        
        def search(node, depth):
            if node is None:
                return
            
            # Calculate distance to current point
            distance = np.linalg.norm(query_point - node.point)
            
            # Update best if this point is closer
            if distance < best[1]:
                best[0] = node.point
                best[1] = distance
            
            # Determine which subtree to search first
            axis = depth % self.k
            diff = query_point[axis] - node.point[axis]
            
            if diff < 0:
                near_subtree, far_subtree = node.left, node.right
            else:
                near_subtree, far_subtree = node.right, node.left
            
            # Search the near subtree
            search(near_subtree, depth + 1)
            
            # Check if we need to search the far subtree
            # (if the splitting plane is within the best distance)
            if abs(diff) < best[1]:
                search(far_subtree, depth + 1)
        
        search(self.root, 0)
        return best[0], best[1]
    
    def range_query(self, lower_bounds, upper_bounds):
        """Find all points within the given range."""
        lower_bounds = np.array(lower_bounds)
        upper_bounds = np.array(upper_bounds)
        results = []
        
        def search(node):
            if node is None:
                return
            
            # Check if current point is in range
            if np.all(node.point >= lower_bounds) and np.all(node.point <= upper_bounds):
                results.append(node.point)
            
            # Determine which subtrees to search
            axis = node.axis
            if lower_bounds[axis] <= node.point[axis]:
                search(node.left)
            if upper_bounds[axis] >= node.point[axis]:
                search(node.right)
        
        search(self.root)
        return results

In [2]:
# Solve ax + by = c, where a, b, c are non-negative integers, and x, y must be non-negative integers.

import math

def solve(a, b, c):
    g = math.gcd(a, b)
    if c % g != 0:
        return None  # No solution exists
    a = a // g 
    b = b // g
    c = c // g 

    x = 0
    while (c - a * x) % b != 0:
        x += 1
    y = (c - a * x) // b
    if y < 0:
        return None
    return x, y

solve(3, 4, 25)

(3, 4)

In [2]:
ord('a')

97

In [3]:
from sortedcontainers import SortedList
pq = SortedList([1, 2, 3, 3, 3, 3, 4, 4, 4, 5])
pq.bisect_right(2)

2

In [4]:
pq.bisect_right(3)

6

In [2]:
from sortedcontainers import SortedList
pq = SortedList([1, 2, 3, 3, 3, 3, 4, 4, 4, 5])
pq.remove(3)
pq

SortedList([1, 2, 3, 3, 3, 4, 4, 4, 5])

In [3]:
sum(pq)

29

In [3]:
pq = SortedList([1, 2, 3, 3, 3, 3, 4, 4, 4, 5])
pq.bisect_left(3)

2

In [4]:
pq.bisect_left(6)

10

In [5]:
len(pq)

10

In [6]:
pq[0]

1

In [8]:
a = {'a': 1, 'b': 2, 'c': 3, 'd': 2}
max(a.values())

3

In [10]:
3 & 1

1

In [1]:
ord('a') - 96

1

In [1]:
ord('0')

48